export const authTypes = {
  SET_BTN_LOADING: "SET_BTN_LOADING",
  SET_PAGE_LOADING: "SET_PAGE_LOADING",
  SET_LOGIN_BTN_LOADING: "SET_LOGIN_BTN_LOADING",
  SET_DARK_THEME: "SET_DARK_THEME",
  SET_TOKEN_IN_LOCALSTORAGE: "SET_TOKEN_IN_LOCALSTORAGE",
  SET_REFRESH_TOKEN_IN_LOCALSTORAGE: "SET_REFRESH_TOKEN_IN_LOCALSTORAGE",
  SET_CONTACT_US: "SET_CONTACT_US",
};

export const healthExpertTypes = {
  SET_CATEGORY_LIST: "SET_CATEGORY_LIST",
  SET_PATIENT_DETAILS: "SET_PATIENT_DETAILS",
  SET_PATIENT_ID: "SET_PATIENT_ID",
  SET_PATIENT_LIST: "SET_PATIENT_LIST",
  SET_SUB_CATEGORY_LIST: "SET_SUB_CATEGORY_LIST",
  SET_DIET_LIST_BY_USER: "SET_DIET_LIST_BY_USER",
  SET_ADD_DIET_PLAN: "SET_ADD_DIET_PLAN",
};

export const homeTypes = {
  SET_ABOUT_DATA: "SET_ABOUT_DATA",
  SET_CONSULTATION_DETAILS: "SET_CONSULTATION_DETAILS",
  SET_PRODUCT_CATEGORY: "SET_PRODUCT_CATEGORY",
  SET_SHOP_BY_CATEGORY_LIST: "SET_SHOP_BY_CATEGORY_LIST",
  SET_SHOP_CATEGORY_DETAILS: "SET_SHOP_CATEGORY_DETAILS",
  SET_SITE_SETTING_DATA: "SET_SITE_SETTING_DATA",
  SET_TERMS_AND_CONDITION: "SET_TERMS_AND_CONDITION",
};

export const orderTypes = {
  SET_ORDER_DETAILS: "SET_ORDER_DETAILS",
  SET_ORDER_ID: "SET_ORDER_ID",
  SET_ORDER_LIST: "SET_ORDER_LIST",
  SET_ORDER_CANCEL: "SET_ORDER_CANCEL",
};

export const userTypes = {
  SET_UPDATE_USER_DETAILS: "SET_UPDATE_USER_DETAILS",
  SET_UPDATE_USER_ADDRESS: "SET_UPDATE_USER_ADDRESS",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  SET_ADDRESS_DETAILS: "SET_ADDRESS_DETAILS",
};

export const productTypes = {
  SET_PRODUCT_LIST: "SET_PRODUCT_LIST",
  SET_PRODUCT_DETAILS: "SET_PRODUCT_DETAILS",
  SET_ADD_TO_CART: "SET_ADD_TO_CART",
  SET_CART_LIST: "SET_CART_LIST",
  SET_CART_LIST_DETAILS: "SET_CART_LIST_DETAILS",
  SET_REMOVE_CART: "SET_REMOVE_CART",
  SET_BLOG_LIST: "SET_BLOG_LIST",
  SET_BLOG_DETAILS: "SET_BLOG_DETAILS",
  SET_WISHLIST: "SET_WISHLIST",
  SET_ADD_WISHLIST: "SET_ADD_WISHLIST",
  SET_REMOVE_WISHLIST: "SET_REMOVE_WISHLIST",
  SET_ORDER_CHECKOUT: "SET_ORDER_CHECKOUT",
  SET_ATTIBUTE_LIST: "SET_ATTIBUTE_LIST",
  SET_BUY_NOW_PRODUCT_DETAILS: "SET_BUY_NOW_PRODUCT_DETAILS",
  SET_PRODUCT_FILTER_VALUES: "SET_PRODUCT_FILTER_VALUES",
};

export const feedbackTypes = {
  SET_ADD_FEEDBACK: "SET_ADD_FEEDBACK",
  SET_APPLY_FEEDBACK: "SET_APPLY_FEEDBACK",
  SET_FEEDBACK_LIST: "SET_FEEDBACK_LIST",
  SET_REPLY_FEEDBACK_MESSAGE: "SET_REPLY_FEEDBACK_MESSAGE",
};
