import "./globals.css";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import Providers from "@/redux/providers";

export const metadata = {
  title: "Bioveda",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
